#include <iostream>
#include <verilated.h>
#include <verilated_vcd_c.h>
#include "Vmac_unit.h" // Generated by Verilator

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    Vmac_unit* dut = new Vmac_unit;

    // Setup Trace
    Verilated::traceEverOn(true);
    VerilatedVcdC* m_trace = new VerilatedVcdC;
    dut->trace(m_trace, 5);
    m_trace->open("sim/waveform.vcd");

    int time = 0;
    auto tick = [&]() {
        dut->clk = 0; dut->eval(); m_trace->dump(time++);
        dut->clk = 1; dut->eval(); m_trace->dump(time++);
    };

    // 1. Reset System
    dut->rst_n = 0;
    dut->en = 0;
    dut->clr = 0;
    tick();
    dut->rst_n = 1;
    tick();

    // 2. Feed Data: (2 * 3) + (4 * 5)
    std::cout << "Starting Calculation..." << std::endl;
    
    // Cycle 1: Input 2 and 3
    dut->en = 1;
    dut->a_in = 2; dut->b_in = 3;
    tick();

    // Cycle 2: Input 4 and 5
    dut->a_in = 4; dut->b_in = 5;
    tick();

    // Cycle 3: Stop feeding, let the last addition finish
    dut->en = 1;
    dut->a_in = 0; dut->b_in = 0;
    tick();

    // 3. Final Result
    // Due to the 2-stage latency, the result (26) should be ready now
    std::cout << "Final Accumulator Output: " << (int)dut->out << std::endl;

    for(int i=0; i<5; i++) tick(); // Trailing cycles for waveform clarity

    m_trace->close();
    delete dut;
    return 0;
}